TECHNICAL_ENTITIES = [
    "LangGraph",
    "CrewAI",
    "OpenTelemetry",
    "FastAPI",
    "Docker",
    "Kubernetes",
    "Random Forest",
    "Linear Regression",
    "Logistic Regression",
    "Decision Tree",
    "XGBoost",
    "LightGBM",
    "CatBoost",
    "CNN",
    "RNN",
    "LSTM",
    "Transformer",
    "BERT",
    "DistilBERT",
    "Machine Learning",
    "Deep Learning",
    "Neural Network",
    "REST API",
    "PostgreSQL",
    "MongoDB",
    "Redis",
    "Kafka",
    "JWT",
    "Microservices"
]
