TECHNICAL_ENTITIES = [
    # Machine Learning
    "Random Forest",
    "Decision Tree",
    "Linear Regression",
    "Logistic Regression",
    "XGBoost",
    "LightGBM",
    "CatBoost",
    "KNN",
    "Support Vector Machine",
    "SVM",
    "PCA",
    "Feature Engineering",
    "Feature Selection",
    "Cross Validation",
    "Hyperparameter Tuning",
    "Gradient Boosting",
    "SMOTE",

    # Deep Learning
    "CNN",
    "RNN",
    "LSTM",
    "GRU",
    "Transformer",
    "Attention Mechanism",
    "Neural Network",
    "Deep Learning",
    "Computer Vision",

    # NLP
    "BERT",
    "DistilBERT",
    "RoBERTa",
    "Tokenization",
    "Embedding",
    "Embeddings",
    "Vector Database",
    "RAG",
    "Prompt Engineering",
    "Fine Tuning",
    "Inference",

    # AI Agent
    "LangGraph",
    "CrewAI",
    "MCP Server",
    "OpenAI API",
    "Agent Workflow",
    "Multi Agent System",

    # Backend
    "FastAPI",
    "Flask",
    "Django",
    "REST API",
    "GraphQL",
    "JWT",
    "OAuth",
    "WebSocket",
    "Microservices",

    # Cloud & DevOps
    "Docker",
    "Kubernetes",
    "Terraform",
    "Jenkins",
    "GitHub Actions",
    "CI/CD",
    "OpenTelemetry",
    "Observability",
    "Service Mesh",
    "Load Balancer",

    # Databases
    "PostgreSQL",
    "MySQL",
    "MongoDB",
    "Redis",
    "Kafka",
    "RabbitMQ",
    "ChromaDB",
    "Pinecone",
    "Milvus"
]
